@baseUrl = http://localhost:5000

###
# @name csrf
GET {{baseUrl}}/api/csrf

###
@csrfToken = {{csrf.response.body.csrfToken}}

###
POST {{baseUrl}}/api/register
Content-Type: application/json
x-csrf-token: {{csrfToken}}

{
  "name": "Debos58",
  "email": "Debos58@example.com",
  "password": "De@206914"
}

###
# @name login
POST {{baseUrl}}/api/login
Content-Type: application/json
x-csrf-token: {{csrfToken}}

{
  "email": "Debos58@example.com",
  "password": "De@206914"
}

###
@token = {{login.response.body.access_token}}

###
POST {{baseUrl}}/api/notes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Note 1",
  "body": "This is the body of Note 1"
}

###
GET {{baseUrl}}/api/notes?skip=0&take=3
Authorization: Bearer {{token}}

// get a single note
###
GET {{baseUrl}}/api/notes/10
Authorization: Bearer {{token}}
###
PATCH {{baseUrl}}/api/notes/10
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
  "title": "Note 10",
  "body": "This is the body of Note 1"
}
### 
DELETE {{baseUrl}}/api/notes/19
Content-Type: application/json
Authorization: Bearer {{token}}
