GET http://localhost:3000

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "name": "Debos",
  "email": "Debos3@example.com",
  "password": "De@206914"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "Debos3@example.com",
  "password": "De@206914"
}
###
POST http://localhost:3000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkRlYm9zM0BleGFtcGxlLmNvbSIsInN1YiI6NiwiaWF0IjoxNzkwOTg5MzAwLCJleHAiOjE3OTA5ODkzNjB9.oGh_8ZVNO4QZZnHn-1sSXnW69XpNibWEG-cDAqpzF6Y

{
  "title": "Note 1",
  "body": "This is the body of Note 1"
}